<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-47P2MTB" failures="1" tests="14" name="test.SwagLabs1LoginTests" time="88.024" errors="0" timestamp="2023-03-01T22:31:55 IST" skipped="0">
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_1ValidId2ValidPwd_OpenedHomepage" time="5.296"/>
  <system-out/>
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_1ValidId2ValidPwd_OpenedHomepage" time="5.331">
    <failure message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at test.SwagLabs1LoginTests.doLogin_1ValidId2ValidPwd_OpenedHomepage(SwagLabs1LoginTests.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- doLogin_1ValidId2ValidPwd_OpenedHomepage -->
  <system-out/>
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_1ValidId2ValidPwd_OpenedHomepage" time="10.044"/>
  <system-out/>
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_1ValidId2ValidPwd_OpenedHomepage" time="5.513"/>
  <system-out/>
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_1ValidId2InvalidPwd_FailedLoginAndVerifyErrorMSG" time="18.966"/>
  <system-out/>
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_1InvalidId2validPwd_FailedLoginAndVerifyErrorMSG" time="5.383"/>
  <system-out/>
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_1InvalidId2InvalidPwd_FailedLoginAndVerifyErrorMSG" time="4.247"/>
  <system-out/>
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_1EmptyId2GivenPwd_FailedLoginAndVerifyWarningMSG" time="6.577"/>
  <system-out/>
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_1EmptyPwd2GivenId_FailedLoginAndVerifyWarningMSG" time="4.731"/>
  <system-out/>
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_1EmptyId2EmptyPwd_FailedLoginAndVerifyWarningMSG" time="4.693"/>
  <system-out/>
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_Clickable_CompletedLogin" time="4.333"/>
  <system-out/>
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_SwagLabsLogo_DisplayedLogoAndVerifyText" time="4.279"/>
  <system-out/>
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_ErrorBoxCancelButton_ClosedErrorOrWarningMSG" time="5.041"/>
  <system-out/>
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_PlaceHolderText_Displayed" time="3.590"/>
  <system-out/>
</testsuite> <!-- test.SwagLabs1LoginTests -->
